name: Triggered

"on":
  workflow_run:
    workflows: [Checks]
    types: [completed]
    branches: [master]

jobs:
  triggered:
    runs-on: ubuntu-latest
    steps:
      - name: info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          env
          jq . "${GITHUB_EVENT_PATH}"
          echo HEAD_SHA=$(gh api /repos/zregvart/testbed/git/matching-refs/heads/master --jq '.[0].object.sha') >> "$GITHUB_ENV"
      - name: see
        run: |
          echo workflow run: ${{github.event.workflow_run.head_sha}}
          echo head:         ${{env.HEAD_SHA}}
      - name: release
        run: echo working
        if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_sha == env.HEAD_SHA) || github.event.workflow_dispatch }}
          